
language: cpp
os: linux
sudo: false
dist: bionic
compiler:
  - gcc
  - clang

cache:
  directories:
    - ~/.ccache
    - qt5

before_install:
  - sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev

install:
  - mkdir -p qt5
  - if [ ! -d qt5/.git ] ; then rm qt5 -Rf ; git clone --branch=5.12.5 git://code.qt.io/qt/qt5.git ; fi
  - pushd qt5
  - if [ ! -d qtbase/.git ] ; then perl init-repository --module-subset=qtbase,qtimageformats,qtmultimedia,qttools ; fi
  - if [ ! -f config.summary ] ; then ./configure -prefix `pwd`/build -opensource -confirm-license -nomake examples -nomake tests ; fi
  - if [ ! -d build ] ; then make -j2 > /dev/null && make install ; fi
  - popd
  - ccache -s

script:
  - mkdir -p build
  - pushd build
  - ../qt5/build/bin/qmake CONFIG+=ccache .. -config release
  - make -j2
  - make install
  - popd
